version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: hiresense-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hiresense-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - JWT_SECRET=super_secret_hiresente_2026_key
      - JWT_ALGORITHM=HS256
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hiresense-web
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
