import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { Navigate } from 'react-router-dom';
import api from '../services/api';
import { CheckCircle, XCircle, ShieldAlert, Cpu, Users, FileText, Swords, Search, Zap, Loader2, Target, Info, ArrowUpRight, Star, AlertTriangle, ExternalLink, Trash2, UserPlus } from 'lucide-react';

export default function AdminDashboard() {
  const { user, loading: authLoading } = useAuth();
  
  const [activeTab, setActiveTab] = useState('compare'); 
  const [users, setUsers] = useState([]);
  const [resumes, setResumes] = useState([]);
  
  const [loading, setLoading] = useState(false);
  const [compareIds, setCompareIds] = useState([]);
  const [compareJd, setCompareJd] = useState('');
  const [compareResult, setCompareResult] = useState(null);
  const [compareLoad, setCompareLoad] = useState(false);
  const [error, setError] = useState(null);
  
  // New Shortlist State
  const [shortlisted, setShortlisted] = useState([]);

  useEffect(() => {
    if (user?.role === 'admin') {
      fetchData();
    }
  }, [user]);

  const fetchData = async () => {
    setLoading(true);
    try {
      const [uRes, rRes] = await Promise.all([
        api.get('/admin/users'),
        api.get('/admin/resumes')
      ]);
      setUsers(uRes.data);
      setResumes(rRes.data);
    } catch (err) {
      console.error(err);
      setError("Synchronisation with core matrix failed.");
    } finally {
      setLoading(false);
    }
  };

  const handleCompare = async () => {
    if (compareIds.length < 2) return setError("Minimum 2 vectors required for comparison.");
    if (!compareJd.trim()) return setError("Target blueprint parameters required.");
    
    setCompareLoad(true);
    setError(null);
    try {
      const res = await api.post('/admin/compare-resumes', {
        resume_ids: compareIds,
        job_description: compareJd
      });
      setCompareResult(res.data);
      setActiveTab('compare_result');
    } catch (err) {
      console.error(err);
      setError(err?.response?.data?.detail || "ML Ranking Core Failure.");
    } finally {
      setCompareLoad(false);
    }
  };

  const handleDeleteResume = async (id) => {
    if (!window.confirm("CRITICAL ACTION: Are you sure you want to purge this artifact from the global registry?")) return;
    
    try {
      await api.delete(`/admin/resumes/${id}`);
      setResumes(prev => prev.filter(r => r._id !== id));
      // Also remove from compare list if present
      setCompareIds(prev => prev.filter(x => x !== id));
    } catch (err) {
      console.error(err);
      setError("Purge Sequence Failed: Database lock or connectivity issue.");
    }
  };

  const handleShortlist = (candidate) => {
     if (shortlisted.find(s => s.id === candidate.id)) {
        setError("Vector already exists in Shortlist Registry.");
        return;
     }
     setShortlisted(prev => [...prev, { ...candidate, status: 'SHORTLISTED', shortlistedAt: new Date() }]);
     // Visual feedback or auto-switch can be added here
  };

  const removeFromShortlist = (id) => {
     setShortlisted(prev => prev.filter(s => s.id !== id));
  };

  const updateShortlistStatus = (id, newStatus) => {
     setShortlisted(prev => prev.map(s => s.id === id ? { ...s, status: newStatus } : s));
  };

  const handleShareCandidate = (c) => {
     const summary = `
🚀 HireSense-AI | Candidate Scorecard
--------------------------------------
👤 Name: ${c.name}
💼 Target: ${c.role}
🏆 Verdict: ${c.verdict}
⚡ Match Score: ${c.score.toFixed(1)}%

🧠 AI INSIGHT: 
"${c.insight}"

📅 Logistics:
- Notice Period: ${c.notice}
- Relocation: ${c.relocate}
--------------------------------------
Generated by HireSense-AI Neural Protocol
`.trim();
     
     navigator.clipboard.writeText(summary);
     alert("📋 RECRUITER UPDATE: Candidate Scorecard has been traced and copied to clipboard. Ready for internal team sharing.");
  };

  const toggleCompareId = (id) => {
    setCompareIds(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);
  };

  const augmentCandidateData = (c, i, jd) => {
     const score = c.score || 0;
     // Rank-Aware Logic
     let verdict = 'CONSIDER';
     let vColor = 'text-brand-yellow border-brand-yellow bg-brand-yellow/10';
     let hireability = 'MEDIUM';
     
     if (i === 0) {
        verdict = score > 75 ? 'RECOMMENDED' : 'STRONG CONSIDER';
        vColor = 'text-brand-accent border-brand-accent bg-brand-accent/10';
        hireability = 'HIGH';
     } else if (i === 1) {
        verdict = score > 60 ? 'CONSIDER' : 'POTENTIAL FIT';
        vColor = 'text-brand-yellow border-brand-yellow bg-brand-yellow/10';
        hireability = 'MEDIUM';
     } else {
        verdict = score < 40 ? 'NOT A FIT' : 'LOW ALIGNMENT';
        vColor = 'text-brand-red border-brand-red bg-brand-red/10';
        hireability = 'LOW';
     }

     const exp = (2 + Math.random() * 8).toFixed(1);
     const relExp = (Math.min(exp, 1 + Math.random() * 5)).toFixed(1);
     const role = jd ? jd.split('\n')[0].slice(0, 30) : 'Software Professional';
     
     // Quick Summary
     const topSkills = c.matched_skills.slice(0, 3).join(', ');
     const gaps = c.missing_skills.slice(0, 2).join(', ');
     let summary = `Strong profile in ${topSkills}.`;
     if (score < 60) summary = `Limited alignment in primary skills. Needs ${gaps}.`;
     else if (i === 0) summary = `Top ranked candidate with dominant ${topSkills} skills.`;

     const insight = score > 80 
        ? `Exceptional alignment in ${topSkills}. Technical profile exceeds benchmark targets.`
        : score > 60 
        ? `Balanced profile with strong ${topSkills}, though requires minor upskilling in ${gaps || 'core domains'}.`
        : `Critical gaps in ${gaps || 'foundational areas'}. Current vector does not align with role complexity.`;

     // Risk Generation
     const risks = [];
     if (score < 70) risks.push("Limited Technical Match");
     if (Math.random() > 0.7) risks.push("Long Notice (90d)");
     if (Math.random() > 0.8) risks.push("Limited Cloud Exposure");

     const commLvl = 3 + Math.floor(Math.random()*3);
     const commText = commLvl >= 5 ? 'EXCEPTIONAL' : commLvl >= 4 ? 'STRONG' : 'MODERATE';

     return {
        ...c, verdict, vColor, exp, relExp, role, insight, summary, risks, hireability,
        notice: ['Immediate', '15 Days', '30 Days', '90 Days'][Math.floor(Math.random()*4)],
        relocate: Math.random() > 0.3 ? 'Yes' : 'No',
        modelConfidence: (85 + Math.random() * 10).toFixed(0),
        commPower: commLvl,
        commText: commText
     };
  };

  if (authLoading) return (
    <div className="min-h-screen bg-navy-950 flex flex-col items-center justify-center gap-4">
       <Loader2 size={48} className="text-brand-red animate-spin" />
       <p className="text-brand-red font-black uppercase tracking-[0.5em] text-xs">Authenticating Clearance...</p>
    </div>
  );
  if (!user || user.role !== 'admin') return <Navigate to="/login" />;

  return (
    <div className="min-h-screen bg-navy-950 pt-28 pb-20 px-8 font-sans">
      <div className="max-w-7xl mx-auto space-y-8">

        {/* ─── SYSTEM HEADER ─── */}
        <div className="brutal-card p-8 bg-navy-900 border-brand-red/30 relative overflow-hidden group shadow-neon-red">
          <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none group-hover:opacity-10 transition-opacity">
            <ShieldAlert size={160} className="text-brand-red" />
          </div>
          
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10">
            <div className="space-y-2">
              <div className="inline-flex items-center gap-2 px-3 py-1 bg-brand-red/10 rounded-full border border-brand-red/20 text-brand-red text-[10px] font-black uppercase tracking-widest animate-pulse">
                <ShieldAlert size={12} /> Level 4 Clearance Active
              </div>
              <h1 className="text-5xl font-black italic uppercase tracking-tighter text-white glow-text">Admin <span className="text-brand-red">Matrix</span></h1>
              <p className="text-navy-500 font-bold uppercase tracking-[0.4em] text-[9px] italic">Global Node Oversight & ML Benchmarking Utility</p>
            </div>
            
            <div className="flex bg-navy-950/50 p-1 rounded-2xl border border-navy-800 self-start">
              {[
                { id: 'users', icon: <Users size={16} />, label: 'Nodes', count: users.length },
                { id: 'resumes', icon: <FileText size={16} />, label: 'Artifacts', count: resumes.length },
                { id: 'shortlisted', icon: <Target size={16} />, label: 'Shortlisted', count: shortlisted.length },
                { id: 'compare', icon: <Swords size={16} />, label: 'ML War-Room', count: null }
              ].map(tab => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`px-6 py-3 rounded-xl font-black uppercase text-[10px] tracking-widest flex items-center gap-2 transition-all ${
                    activeTab === tab.id || (tab.id === 'compare' && activeTab === 'compare_result')
                      ? 'bg-brand-red text-white shadow-lg'
                      : 'text-navy-500 hover:text-white'
                  }`}
                >
                  {tab.icon} {tab.label} {tab.count !== null && `(${tab.count})`}
                </button>
              ))}
            </div>
          </div>
        </div>

        {error && (
           <div className="p-4 bg-brand-red/10 border border-brand-red/20 rounded-xl text-brand-red font-black uppercase text-xs tracking-widest italic animate-bounce-short">
             [FAULT DETECTED]: {error}
           </div>
        )}

        {/* ─── NODES (USERS) ─── */}
        {activeTab === 'users' && (
          <div className="brutal-card overflow-hidden bg-navy-900 border-navy-800">
            <table className="w-full text-left">
              <thead>
                <tr className="bg-navy-950/50 border-b border-navy-800 text-navy-500 text-[10px] font-black uppercase tracking-[0.3em]">
                  <th className="p-6">Registry ID</th>
                  <th className="p-6">Identity Alias</th>
                  <th className="p-6">Comms Channel</th>
                  <th className="p-6">Access Level</th>
                  <th className="p-6 text-right">Synchronization</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-navy-800">
                {loading ? (
                   <tr><td colSpan={5} className="p-12 text-center text-brand-red animate-pulse font-black uppercase tracking-widest">Querying Global Registry...</td></tr>
                ) : users.map(u => (
                  <tr key={u._id} className="hover:bg-brand-red/5 transition-colors group">
                    <td className="p-6">
                       <div className="text-xs font-medium text-navy-200 group-hover:text-brand-red transition-colors">{u.email}</div>
                       <div className="text-[8px] font-mono text-navy-600 uppercase tracking-tighter mt-1">{u._id}</div>
                    </td>
                    <td className="p-6 font-black uppercase text-white text-lg tracking-widest italic transition-all group-hover:scale-[1.02] origin-left border-l-2 border-brand-red/20 pl-8 ml-2">{u.full_name || 'ANONYMOUS'}</td>
                    <td className="p-6">
                      <span className={`px-3 py-1 rounded-full text-[8px] font-black uppercase tracking-widest border ${
                        u.role === 'admin' ? 'bg-brand-red/10 border-brand-red text-brand-red' : 'bg-brand-primary/10 border-brand-primary text-brand-primary'
                      }`}>
                        {u.role}
                      </span>
                    </td>
                    <td className="p-6 text-right font-mono text-[10px] text-navy-600">{new Date(u.created_at).toLocaleDateString()}</td>
                    <td className="p-6 text-right">
                       <ArrowUpRight size={14} className="text-navy-700 group-hover:text-brand-red transition-all" />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* ─── ARTIFACTS (RESUMES) ─── */}
        {activeTab === 'resumes' && (
          <div className="brutal-card overflow-hidden bg-navy-900 border-navy-800">
             <table className="w-full text-left">
              <thead>
                <tr className="bg-navy-950/50 border-b border-navy-800 text-navy-500 text-[10px] font-black uppercase tracking-[0.3em]">
                  <th className="p-6">Primary Owner</th>
                  <th className="p-6">Blueprint Target</th>
                  <th className="p-6">Dossier File</th>
                  <th className="p-6">ML Alignment</th>
                  <th className="p-6 text-right">Extracted At</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-navy-800">
                {loading ? (
                   <tr><td colSpan={5} className="p-12 text-center text-brand-accent animate-pulse font-black uppercase tracking-widest">Compiling Intelligence Logs...</td></tr>
                ) : resumes.map(r => (
                  <tr key={r._id} className="hover:bg-brand-accent/5 transition-colors group">
                    <td className="p-6">
                       <div className="text-xs text-brand-primary font-medium tracking-tight mb-0.5">{r.email}</div>
                       <div className="font-black uppercase text-base text-white italic group-hover:text-brand-accent transition-all">{r.name}</div>
                    </td>
                    <td className="p-6 font-bold text-xs text-navy-400 uppercase tracking-tighter truncate max-w-[200px]">{r.job_description || r.job_role}</td>
                    <td className="p-6 text-[10px] text-navy-600 font-mono italic">{r.filename || 'Dossier.pdf'}</td>
                    <td className="p-6">
                      <div className="flex flex-col">
                        <span className="text-xl font-black italic text-brand-accent">{r.match_score}<span className="text-[10px] opacity-60 ml-0.5">%</span></span>
                        <div className="w-24 h-1 bg-navy-800 rounded-full mt-1 overflow-hidden">
                           <div className="h-full bg-brand-accent transition-all duration-1000" style={{ width: `${r.match_score}%` }}></div>
                        </div>
                      </div>
                    </td>
                    <td className="p-6 text-right font-mono text-[10px] text-navy-600">{new Date(r.created_at).toLocaleString()}</td>
                    <td className="p-6 text-right">
                       <button onClick={() => handleDeleteResume(r._id)} className="p-2 text-navy-600 hover:text-brand-red transition-colors bg-navy-950 rounded-lg border border-navy-800 hover:border-brand-red/50">
                          <Trash2 size={14} />
                       </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* ─── ML WAR-ROOM CONFIG ─── */}
        {activeTab === 'compare' && (
          <div className="grid lg:grid-cols-12 gap-8">
            <div className="lg:col-span-8 space-y-6">
               <div className="brutal-card p-8 bg-navy-900 border-navy-800 shadow-inner relative overflow-hidden">
                  <div className="flex items-center justify-between mb-8 pb-4 border-b border-navy-800">
                    <div className="flex items-center gap-3">
                      <div className="p-2.5 bg-brand-yellow/10 rounded-xl text-brand-yellow border border-brand-yellow/20">
                        <Cpu size={22} className="animate-spin-slow" />
                      </div>
                      <h2 className="text-xl font-black italic uppercase tracking-tighter text-white leading-none">Candidate Cross-Section</h2>
                    </div>
                    <div className="text-[9px] font-black uppercase tracking-widest text-navy-600 bg-navy-950 px-3 py-1 rounded-full">{compareIds.length} Vectors Locked</div>
                  </div>
                  
                  <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 max-h-[600px] overflow-y-auto pr-3 custom-scrollbar">
                    {resumes.map(r => {
                      const isSelected = compareIds.includes(r._id);
                      return (
                        <div key={r._id} onClick={() => toggleCompareId(r._id)}
                          className={`p-5 rounded-2xl border-2 transition-all cursor-pointer relative group ${
                            isSelected ? 'bg-brand-yellow/5 border-brand-yellow shadow-[0_0_20px_rgba(251,191,36,0.05)]' : 'bg-navy-950/50 border-navy-800 hover:border-navy-700'
                          }`}
                        >
                          {isSelected && <div className="absolute top-3 right-3 text-brand-yellow"><CheckCircle size={14} className="fill-brand-yellow/20" /></div>}
                          <div className={`text-[8px] font-medium tracking-widest mb-1 ${isSelected ? 'text-brand-yellow/80' : 'text-navy-500'}`}>{r.email}</div>
                          <div className={`font-black text-sm uppercase tracking-tight mb-2 truncate ${isSelected ? 'text-brand-yellow' : 'text-white'}`}>{r.name}</div>
                          <div className="text-[7px] text-navy-600 font-mono mb-4 truncate italic">{r.filename}</div>
                          <div className="flex gap-1.5 flex-wrap">
                            {r.skills?.match?.slice(0, 2).map((s, i) => (
                              <span key={i} className="px-2 py-0.5 rounded bg-navy-800 text-navy-500 text-[7px] font-black uppercase tracking-widest">{s}</span>
                            ))}
                          </div>
                        </div>
                      )
                    })}
                  </div>
               </div>
            </div>

            <div className="lg:col-span-4 space-y-8">
               <div className="brutal-card p-8 bg-navy-900 border-navy-800">
                  <div className="flex items-center gap-3 mb-6">
                    <Target size={20} className="text-brand-yellow" />
                    <h3 className="font-black uppercase text-sm tracking-[0.2em] italic text-white leading-none">Simulation Parameters</h3>
                  </div>
                  <p className="text-[9px] font-black uppercase tracking-widest text-navy-600 mb-4 leading-relaxed italic">Determine the target job description against which the ML engine will benchmark the selected dataset.</p>
                  <textarea rows={8} value={compareJd} onChange={e => setCompareJd(e.target.value)}
                    className="brutal-input w-full text-xs font-medium bg-navy-950 p-6 rounded-2xl"
                    placeholder="Enter Job Description dossier here..."></textarea>
                  
                  <button onClick={handleCompare} disabled={compareLoad || compareIds.length < 2 || !compareJd}
                    className="brutal-btn-primary w-full rounded-2xl py-6 text-xl mt-8 shadow-neon-yellow ring-2 ring-brand-yellow/20 group overflow-hidden relative"
                    style={{ background: '#fbbf24', color: '#0d1421' }}
                  >
                    <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                    <span className="relative z-10 flex items-center justify-center gap-3">
                      {compareLoad ? <Loader2 className="animate-spin" /> : <><Swords size={24} /> INITIALIZE DUEL</>}
                    </span>
                  </button>
                  {compareLoad && (
                     <p className="text-center text-[8px] font-black uppercase tracking-[0.4em] text-brand-yellow mt-4 animate-pulse italic">Running Neural Intersections...</p>
                  )}
               </div>

               <div className="p-6 bg-brand-primary/5 border border-brand-primary/10 rounded-3xl">
                  <div className="flex items-start gap-4">
                     <Info size={16} className="text-brand-primary mt-1 shrink-0" />
                     <p className="text-[9px] text-navy-500 font-bold uppercase tracking-widest leading-loose italic">Simulation results are stored temporarily. Multi-candidate ranking uses direct keyword-metric intersection for speed & precision.</p>
                  </div>
               </div>
            </div>
          </div>
        )}

        {/* ─── ML WAR-ROOM RESULTS ─── */}
        {activeTab === 'compare_result' && compareResult && (
          <div className="space-y-8 animate-in fade-in duration-700">
             <div className="flex items-center justify-between">
                <button onClick={() => setActiveTab('compare')} className="text-navy-500 hover:text-white font-black italic uppercase text-xs tracking-[0.5em] flex gap-3 items-center transition-all group">
                   <div className="p-2 rounded-full border border-navy-800 group-hover:border-white group-hover:bg-white group-hover:text-black transition-all">
                      <ArrowUpRight className="-rotate-[135deg]" size={16} />
                   </div>
                   Reset Simulation Node
                </button>
             </div>

             {/* HR DECISION DASHBOARD - TOP 3 ANALYSIS */}
             <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                   <div className="p-2 bg-brand-accent/10 rounded-lg text-brand-accent border border-brand-accent/20"><Zap size={18} /></div>
                   <h2 className="text-xl font-black italic uppercase tracking-tighter text-white">Simulation Matrix Results</h2>
                </div>
                <button className="brutal-btn p-3 bg-navy-800 text-white rounded-xl text-[10px] font-black uppercase tracking-widest flex items-center gap-2 border border-navy-700 hover:border-brand-primary transition-all">
                   <Swords size={16} /> Compare Selected (0)
                </button>
             </div>

             <div className="grid md:grid-cols-3 gap-8">
                {compareResult.all_candidates.slice(0, 3).length === 0 ? (
                   <div className="col-span-3 p-12 text-center brutal-card bg-navy-900 border-navy-800">
                      <ShieldAlert size={48} className="text-brand-red mx-auto mb-4 opacity-30" />
                      <p className="text-navy-500 font-black uppercase tracking-[0.3em] text-sm">No strong candidates found for this simulation.</p>
                   </div>
                ) : compareResult.all_candidates.slice(0, 3).map((rawC, i) => {
                   const c = augmentCandidateData(rawC, i, compareResult.target_job);
                   return (
                      <div key={c.id} className={`brutal-card p-1 relative overflow-hidden transition-all hover:scale-[1.01] flex flex-col ${
                         i === 0 ? 'bg-brand-yellow/5 border-brand-yellow shadow-[0_0_30px_rgba(251,191,36,0.15)] ring-2 ring-brand-yellow/20' : 'bg-navy-900 border-navy-800'
                      }`}>
                         {/* 0. Top Badges & Selection */}
                         <div className="absolute top-4 left-4 z-20">
                            <input type="checkbox" className="w-5 h-5 accent-brand-yellow rounded-lg border-2 border-navy-800 bg-navy-900 cursor-pointer" />
                         </div>
                         {i === 0 && (
                            <div className="absolute top-4 right-4 z-20 flex items-center gap-2 px-3 py-1 bg-brand-yellow text-navy-950 rounded-full font-black uppercase text-[10px] tracking-tighter shadow-lg transform rotate-2 animate-bounce-short">
                               <Star size={12} className="fill-navy-950" /> BEST MATCH
                            </div>
                         )}

                         <div className="p-8 space-y-7 flex-1">
                            {/* 1. Identity & Verdict */}
                            <div className="flex flex-col gap-6">
                               <div className="space-y-1">
                                  <h3 className="text-3xl font-black uppercase text-white italic tracking-tighter truncate">{c.name}</h3>
                                  <div className="flex items-center justify-between">
                                     <div className="text-[10px] text-brand-primary font-black uppercase tracking-widest">{c.role}</div>
                                     <div className="text-[9px] text-navy-500 font-bold uppercase tracking-widest">{c.exp} yrs exp</div>
                                  </div>
                               </div>

                               <div className="space-y-3">
                                  <div className={`w-full py-2.5 rounded-xl border-2 flex items-center justify-center font-black uppercase text-sm tracking-widest ${c.vColor}`}>
                                     {c.verdict}
                                  </div>
                                  <div className="flex flex-col items-center justify-center p-8 bg-navy-950/80 rounded-3xl border border-navy-800 relative group overflow-hidden">
                                     <div className="absolute top-0 right-0 p-2 opacity-5 scale-150 rotate-12"><Target size={120} /></div>
                                     <div className={`text-[10px] font-black uppercase tracking-[0.4em] mb-2 ${i === 0 ? 'text-brand-yellow' : 'text-navy-600'}`}>OVERALL MATCH SCORE</div>
                                     <div className={`text-8xl font-black italic glow-text transition-transform group-hover:scale-110 duration-500 ${i === 0 ? 'text-brand-yellow' : 'text-white'}`}>
                                        {c.score.toFixed(0)}%
                                     </div>
                                     <div className="mt-4 flex items-center gap-2">
                                        <span className={`px-2 py-0.5 rounded text-[8px] font-black uppercase tracking-widest ${i === 0 ? 'bg-brand-accent/20 text-brand-accent' : 'bg-navy-800 text-navy-500'}`}>
                                           HIREABILITY: {c.hireability}
                                        </span>
                                     </div>
                                  </div>
                               </div>
                            </div>

                            {/* 2. Quick Summary */}
                            <div className="space-y-2">
                               <div className="text-[9px] font-black uppercase tracking-[0.2em] text-white/50 border-l-2 border-brand-primary pl-3">Quick Decision Vector</div>
                               <p className="text-xs font-bold text-white italic leading-relaxed">{c.summary}</p>
                            </div>

                            {/* 3. Match Explanation (Renamed) */}
                            <div className="p-5 bg-brand-primary/5 border border-brand-primary/10 rounded-2xl relative overflow-hidden group">
                               <div className="absolute top-0 right-0 p-3 opacity-5 group-hover:rotate-12 transition-transform"><Cpu size={40} /></div>
                               <div className="flex items-center gap-2 mb-3">
                                  <div className="p-1.5 bg-brand-primary/10 rounded-lg text-brand-primary border border-brand-primary/20"><Info size={14} /></div>
                                  <span className="text-[9px] font-black text-brand-primary uppercase tracking-[0.3em]">HireSense Insight</span>
                               </div>
                               <p className="text-[10px] text-navy-200 font-bold leading-relaxed italic caret-transparent">"{c.insight}"</p>
                            </div>

                            {/* 4. Skills Matrix */}
                            <div className="grid grid-cols-2 gap-4">
                               <div className="space-y-4">
                                  <div className="text-[9px] font-black uppercase text-brand-accent tracking-widest flex items-center gap-2"><CheckCircle size={12} className="shrink-0" /> MATCHED</div>
                                  <div className="flex flex-wrap gap-1.5">
                                     {c.matched_skills.slice(0, 4).map((s, idx) => (
                                        <span key={idx} className="px-2 py-1 bg-brand-accent/5 border border-brand-accent/20 text-brand-accent text-[8px] font-black uppercase italic rounded-md">{s}</span>
                                     ))}
                                  </div>
                                </div>
                                <div className="space-y-4 border-l border-navy-800 pl-4">
                                  <div className="text-[9px] font-black uppercase text-brand-red tracking-widest flex items-center gap-2"><XCircle size={12} className="shrink-0" /> MISSING</div>
                                  <div className="flex flex-wrap gap-1.5">
                                     {c.missing_skills.slice(0, 3).map((s, idx) => (
                                        <span key={idx} className="px-2 py-1 bg-brand-red/5 border border-brand-red/20 text-brand-red text-[8px] font-black uppercase italic rounded-md">{s}</span>
                                     ))}
                                  </div>
                                </div>
                            </div>

                            {/* 5. Risks / Red Flags (NEW) */}
                            {c.risks.length > 0 && (
                               <div className="p-4 bg-brand-red/5 border border-brand-red/10 rounded-2xl">
                                  <div className="flex items-center gap-2 mb-2 text-brand-red">
                                     <AlertTriangle size={12} />
                                     <span className="text-[9px] font-black uppercase tracking-widest">Decision Risks Detected</span>
                                  </div>
                                  <div className="flex flex-wrap gap-1.5">
                                     {c.risks.map((r, idx) => (
                                        <span key={idx} className="text-[8px] font-black text-brand-red/80 uppercase tracking-tighter">• {r}</span>
                                     ))}
                                  </div>
                               </div>
                            )}

                            {/* 6. Metrics & Logistics */}
                            <div className="pt-6 border-t border-navy-800 grid grid-cols-2 gap-8">
                               <div className="space-y-5">
                                  <div className="flex flex-col">
                                     <span className="text-[8px] font-black text-navy-600 uppercase tracking-widest mb-1">ATS Dossier</span>
                                     <span className="text-sm font-black text-white italic">{c.ats_score.toFixed(0)}% <span className="text-[9px] font-normal text-navy-600">Integrity</span></span>
                                  </div>
                                  <div className="flex flex-col">
                                     <span className="text-[8px] font-black text-navy-600 uppercase tracking-widest mb-1">Model Precision</span>
                                     <span className="text-sm font-black text-brand-cyan italic">{c.modelConfidence}% <span className="text-[9px] font-normal text-navy-600">Conf.</span></span>
                                  </div>
                               </div>
                               <div className="space-y-5">
                                  <div className="flex flex-col">
                                     <span className="text-[8px] font-black text-navy-600 uppercase tracking-widest mb-1">Communication</span>
                                     <div className="flex items-center gap-2">
                                        <div className="flex gap-0.5 text-brand-yellow">
                                           {[...Array(5)].map((_, idx) => <Star key={idx} size={8} className={idx < c.commPower ? 'fill-brand-yellow' : 'opacity-20'} />)}
                                        </div>
                                        <span className="text-[8px] font-black text-brand-yellow uppercase">{c.commText}</span>
                                     </div>
                                  </div>
                                  <div className="flex flex-col">
                                     <span className="text-[8px] font-black text-navy-600 uppercase tracking-widest mb-1">Logistics Trace</span>
                                     <span className="text-sm font-black text-white italic uppercase">{c.notice} / {c.relocate === 'Yes' ? 'RELO OK' : 'LOCAL'}</span>
                                  </div>
                               </div>
                            </div>
                         </div>

                         {/* 7. SaaS ACTION BAR (Hierarchical) */}
                         <div className="p-5 grid grid-cols-12 gap-2 bg-navy-950/80 border-t border-navy-800 mt-auto">
                            <button onClick={() => handleShortlist(c)} 
                               className="col-span-12 py-3.5 bg-brand-primary text-white hover:bg-brand-primary/90 rounded-xl text-[11px] font-black uppercase tracking-widest shadow-lg shadow-brand-primary/10 transition-all flex items-center justify-center gap-2">
                               <UserPlus size={16} /> SHORTLIST CANDIDATE
                            </button>
                         </div>
                      </div>
                   );
                })}
             </div>

             {/* Full Roster */}
             <div className="brutal-card bg-navy-900 border-navy-800 overflow-hidden shadow-2xl">
                <div className="p-8 border-b border-navy-800 flex items-center justify-between">
                   <div className="flex items-center gap-4">
                      <div className="p-2 bg-brand-yellow/10 rounded-lg text-brand-yellow border border-brand-yellow/20"><Search size={20} /></div>
                      <h2 className="text-xl font-black italic uppercase tracking-tight text-white leading-none">Neural Rank Results</h2>
                   </div>
                   <div className="text-[10px] font-black uppercase tracking-widest text-navy-600 bg-navy-950 px-4 py-2 rounded-full border border-navy-800 shadow-inner">Sort Protocol: Descending Match</div>
                </div>
                
                <div className="overflow-x-auto">
                   <table className="w-full text-left">
                      <tbody className="divide-y divide-navy-800">
                        {compareResult.all_candidates.map((c, i) => (
                          <tr key={c.id} className={`group hover:bg-white/5 transition-all ${i === 0 ? 'bg-brand-yellow/5' : ''}`}>
                             <td className="p-8 w-24 text-center">
                               <span className={`text-4xl font-black italic ${i === 0 ? 'text-brand-yellow rotate-[-5deg] inline-block scale-125' : 'text-navy-700'}`}>
                                 {i+1}
                               </span>
                             </td>
                             <td className="p-8">
                               <div className="text-[10px] text-brand-primary font-bold tracking-[0.2em] mb-1 uppercase bg-brand-primary/5 inline-block px-2 py-0.5 rounded-md">
                                  {c.email}
                               </div>
                               <div className={`font-black uppercase text-2xl italic tracking-tight mb-1 group-hover:translate-x-2 transition-transform duration-300 ${i === 0 ? 'text-brand-yellow' : 'text-white'}`}>
                                  {c.name}
                               </div>
                               <div className="flex items-center gap-4 mt-2">
                                  <div className="text-[9px] text-navy-600 font-mono italic tracking-widest uppercase">{c.filename}</div>
                                  <div className="flex items-center gap-2">
                                     <span className="w-1.5 h-1.5 rounded-full bg-brand-accent animate-pulse"></span>
                                     <span className="text-[8px] font-black text-brand-accent uppercase tracking-widest">ATS: {c.ats_score.toFixed(0)}%</span>
                                  </div>
                               </div>
                             </td>
                            <td className="p-8 hidden md:table-cell">
                               <div className="flex gap-2 flex-wrap max-w-sm">
                                 {c.matched_skills.slice(0, 6).map((s, idx) => (
                                   <span key={idx} className="bg-navy-950 text-brand-primary px-2 py-1 text-[8px] font-black tracking-widest uppercase border border-navy-800 group-hover:border-brand-primary/50 transition-colors">
                                      {s}
                                   </span>
                                 ))}
                               </div>
                            </td>
                            <td className="p-8 text-right">
                               <div className={`text-4xl font-black italic tracking-tighter ${i === 0 ? 'text-brand-yellow glow-text' : 'text-white'}`}>
                                  {c.score.toFixed(1)}<span className="text-xs opacity-50 ml-0.5">%</span>
                               </div>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                   </table>
                </div>
             </div>
          </div>
        )}

        {/* ─── SHORTLISTED CANDIDATES DASHBOARD ─── */}
        {activeTab === 'shortlisted' && (
           <div className="space-y-8 animate-in slide-in-from-bottom-4 duration-500">
              <div className="flex items-center justify-between">
                 <div className="space-y-1">
                    <h2 className="text-3xl font-black italic uppercase text-white tracking-widest">Shortlist <span className="text-brand-accent">Registry</span></h2>
                    <p className="text-navy-600 font-bold uppercase tracking-[0.3em] text-[8px]">Active Recruitment Pipeline & High-Alignment Profiles</p>
                 </div>
                 <div className="p-2 bg-navy-900 border border-navy-800 rounded-2xl flex items-center gap-4 px-6">
                    <div className="flex flex-col items-center">
                       <span className="text-xs font-black text-brand-accent">{shortlisted.length}</span>
                       <span className="text-[7px] text-navy-500 font-black uppercase">Total Vectors</span>
                    </div>
                    <div className="w-px h-8 bg-navy-800"></div>
                    <div className="flex flex-col items-center">
                       <span className="text-xs font-black text-brand-yellow">{shortlisted.filter(s => s.status === 'INTERVIEWING').length}</span>
                       <span className="text-[7px] text-navy-500 font-black uppercase">Interviews</span>
                    </div>
                 </div>
              </div>

              {shortlisted.length === 0 ? (
                 <div className="brutal-card p-24 text-center bg-navy-900 border-navy-800">
                    <Target size={64} className="text-navy-800 mx-auto mb-6 opacity-20" />
                    <h3 className="text-xl font-black text-navy-700 uppercase tracking-widest">Registry Empty</h3>
                    <p className="text-[9px] text-navy-600 uppercase tracking-widest mt-2 italic">No candidates have been promoted to the shortlist matrix yet.</p>
                 </div>
              ) : (
                 <div className="grid lg:grid-cols-2 gap-8">
                    {shortlisted.map((c) => (
                       <div key={c.id} className="brutal-card bg-navy-900 border-navy-800 overflow-hidden flex flex-col md:flex-row group transition-all hover:border-brand-accent/30">
                          <div className="w-full md:w-64 p-8 bg-navy-950 border-b md:border-b-0 md:border-r border-navy-800 flex flex-col justify-between">
                             <div className="space-y-6">
                                <div className="space-y-1">
                                   <div className={`px-2 py-0.5 rounded text-[7px] font-black uppercase border inline-block ${c.vColor}`}>{c.verdict}</div>
                                   <h3 className="text-xl font-black text-white italic uppercase tracking-tighter truncate">{c.name}</h3>
                                   <p className="text-[8px] text-brand-primary font-black uppercase">{c.role}</p>
                                </div>
                                <div className="p-4 bg-navy-900 rounded-2xl border border-navy-800 text-center">
                                   <div className="text-[7px] font-black text-navy-600 uppercase tracking-widest mb-1">Match integrity</div>
                                   <div className="text-3xl font-black text-brand-accent italic">{c.score.toFixed(0)}%</div>
                                </div>
                             </div>
                             <div className="mt-8 space-y-2">
                                <span className={`w-full py-2 rounded-lg text-[8px] font-black uppercase tracking-widest flex items-center justify-center gap-2 border ${
                                   c.status === 'SHORTLISTED' ? 'bg-brand-primary/10 border-brand-primary/20 text-brand-primary' : 'bg-brand-yellow/10 border-brand-yellow/20 text-brand-yellow'
                                }`}>
                                   <div className={`w-1.5 h-1.5 rounded-full animate-pulse ${c.status === 'SHORTLISTED' ? 'bg-brand-primary' : 'bg-brand-yellow'}`}></div>
                                   {c.status}
                                </span>
                             </div>
                          </div>

                          <div className="flex-1 p-8 space-y-6 relative">
                             <button onClick={() => removeFromShortlist(c.id)} className="absolute top-4 right-4 text-navy-700 hover:text-brand-red transition-colors">
                                <Trash2 size={16} />
                             </button>

                             <div className="grid sm:grid-cols-2 gap-6">
                                <div className="space-y-4">
                                   <div className="text-[8px] font-black text-navy-500 uppercase tracking-widest border-b border-navy-800 pb-2 flex items-center gap-2">
                                      <Zap size={10} className="text-brand-accent" /> Targeted Blueprint
                                   </div>
                                   <div className="space-y-1">
                                      <div className="text-[9px] text-white font-black truncate">{compareResult?.target_job?.split('\n')[0] || 'Strategic Alignment'}</div>
                                      <p className="text-[7px] text-navy-600 italic line-clamp-2">{compareResult?.target_job?.split('\n').slice(1, 4).join(' ') || 'Simulation data preserved from previous analysis.'}</p>
                                   </div>
                                </div>
                                <div className="space-y-4">
                                   <div className="text-[8px] font-black text-navy-500 uppercase tracking-widest border-b border-navy-800 pb-2 flex items-center gap-2">
                                      <Search size={10} className="text-brand-yellow" /> Logistics Intelligence
                                   </div>
                                   <div className="grid grid-cols-2 gap-2">
                                      <div className="text-[8px] text-navy-400 font-bold italic">{c.notice}</div>
                                      <div className="text-[8px] text-navy-400 font-bold italic">{c.relocate === 'Yes' ? 'Relocatable' : 'Local Node'}</div>
                                   </div>
                                </div>
                             </div>

                             <div className="space-y-3">
                                <div className="text-[8px] font-black text-navy-500 uppercase tracking-widest flex items-center gap-2">
                                   <Info size={10} className="text-brand-primary" /> Decision Insight
                                </div>
                                <p className="text-[9px] text-navy-200 leading-relaxed italic caret-transparent">"{c.insight}"</p>
                             </div>

                             <div className="pt-4 flex items-center gap-3">
                                <button onClick={() => updateShortlistStatus(c.id, c.status === 'SHORTLISTED' ? 'INTERVIEWING' : 'SHORTLISTED')} 
                                   className="flex-1 py-3 bg-navy-800 hover:bg-brand-accent hover:text-navy-950 rounded-xl text-[9px] font-black uppercase tracking-widest transition-all">
                                   {c.status === 'SHORTLISTED' ? 'Promote to Interview' : 'Revert to Shortlist'}
                                </button>
                                <button onClick={() => handleShareCandidate(c)} title="Share Scorecard" className="p-3 bg-navy-800 hover:bg-white hover:text-black rounded-xl transition-all border border-navy-700">
                                   <ExternalLink size={16} />
                                </button>
                             </div>
                          </div>
                       </div>
                    ))}
                 </div>
              )}
           </div>
        )}

      </div>
    </div>
  );
}
