name: Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend
      run: |
        docker build -t hiresense-backend:latest ./backend

    - name: Build Frontend
      run: |
        docker build -t hiresense-frontend:latest ./frontend
